<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="181" started-at="2017-12-13T09:31:04Z" finished-at="2017-12-13T09:31:04Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="181" started-at="2017-12-13T09:31:04Z" finished-at="2017-12-13T09:31:04Z">
      <class name="com.testapi.cas.NewTest">
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:com.testapi.cas.NewTest@457e2f02]" name="beforeTest" is-config="true" duration-ms="9" started-at="2017-12-13T17:31:04Z" finished-at="2017-12-13T17:31:04Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method status="FAIL" signature="f(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.testapi.cas.NewTest@457e2f02]" name="f" duration-ms="0" started-at="2017-12-13T17:31:04Z" data-provider="DP1" finished-at="2017-12-13T17:31:04Z">
          <exception class="org.testng.TestNGException">
            <message>
              <![CDATA[Data Provider public java.lang.Object[][] com.testapi.cas.NewTest.createData() throws java.io.IOException returned a null value]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.TestNGException: Data Provider public java.lang.Object[][] com.testapi.cas.NewTest.createData() throws java.io.IOException returned a null valueat org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:133)at org.testng.internal.Parameters.handleParameters(Parameters.java:706)at org.testng.internal.ParameterHandler.handleParameters(ParameterHandler.java:49)at org.testng.internal.ParameterHandler.createParameters(ParameterHandler.java:37)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:914)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
            </full-stacktrace>
          </exception> <!-- org.testng.TestNGException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- f -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:com.testapi.cas.NewTest@457e2f02]" name="afterTest" is-config="true" duration-ms="1" started-at="2017-12-13T17:31:04Z" finished-at="2017-12-13T17:31:04Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
      </class> <!-- com.testapi.cas.NewTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
